# Generated by Django 2.2 on 2021-06-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_auto_20210601_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
